M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu22.10.1} date Mon 03 Jul 2023 11:12:40 PM PDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-03T23:12:40-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu22.10.1
; #@! TF.FileFunction,Plated,3,4,Blind
FMAT,2
INCH
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.0157
%
G90
G05
T1
X3.7972Y-2.5925
T0
M30
